#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 148
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 1
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 24

enum ts_symbol_identifiers {
  sym_ident = 1,
  anon_sym_var = 2,
  anon_sym_LPAREN = 3,
  aux_sym_fullVarDecl_token1 = 4,
  anon_sym_RPAREN = 5,
  anon_sym_EQ = 6,
  anon_sym_STAR = 7,
  anon_sym_COMMA = 8,
  anon_sym_COLON = 9,
  anon_sym_DOT_DOT = 10,
  anon_sym_COLON_EQ = 11,
  anon_sym_fn = 12,
  anon_sym_LBRACE = 13,
  anon_sym_SEMI = 14,
  anon_sym_RBRACE = 15,
  anon_sym_COLON_COLON = 16,
  sym_decNumber = 17,
  sym_hexNumber = 18,
  aux_sym_realNumber_token1 = 19,
  aux_sym_realNumber_token2 = 20,
  aux_sym_realNumber_token3 = 21,
  anon_sym_SQUOTE = 22,
  aux_sym_charLiteral_token1 = 23,
  anon_sym_DQUOTE = 24,
  aux_sym_escSeq_token1 = 25,
  aux_sym_escSeq_token2 = 26,
  sym_comment = 27,
  sym_program = 28,
  sym_fullVarDecl = 29,
  sym_varDeclItem = 30,
  sym_identList = 31,
  sym_typedIdentList = 32,
  sym_type = 33,
  sym_fnDecl = 34,
  sym_methodDecl = 35,
  sym_rcvSignature = 36,
  sym_exprList = 37,
  sym_signature = 38,
  sym_block = 39,
  sym_designator = 40,
  sym_primary = 41,
  sym_qualIdent = 42,
  sym_builtinCall = 43,
  sym_realNumber = 44,
  sym_stringLiteral = 45,
  sym_escSeq = 46,
  aux_sym_program_repeat1 = 47,
  aux_sym_fullVarDecl_repeat1 = 48,
  aux_sym_identList_repeat1 = 49,
  aux_sym_exprList_repeat1 = 50,
  aux_sym_block_repeat1 = 51,
  aux_sym_charLiteral_repeat1 = 52,
  alias_sym_shortVarDecl = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [anon_sym_var] = "var",
  [anon_sym_LPAREN] = "(",
  [aux_sym_fullVarDecl_token1] = "fullVarDecl_token1",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_STAR] = "*",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_fn] = "fn",
  [anon_sym_LBRACE] = "{",
  [anon_sym_SEMI] = ";",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON_COLON] = "::",
  [sym_decNumber] = "decNumber",
  [sym_hexNumber] = "hexNumber",
  [aux_sym_realNumber_token1] = "realNumber_token1",
  [aux_sym_realNumber_token2] = "realNumber_token2",
  [aux_sym_realNumber_token3] = "realNumber_token3",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_charLiteral_token1] = "charLiteral_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_escSeq_token1] = "escSeq_token1",
  [aux_sym_escSeq_token2] = "escSeq_token2",
  [sym_comment] = "comment",
  [sym_program] = "program",
  [sym_fullVarDecl] = "fullVarDecl",
  [sym_varDeclItem] = "varDeclItem",
  [sym_identList] = "identList",
  [sym_typedIdentList] = "typedIdentList",
  [sym_type] = "type",
  [sym_fnDecl] = "fnDecl",
  [sym_methodDecl] = "methodDecl",
  [sym_rcvSignature] = "rcvSignature",
  [sym_exprList] = "exprList",
  [sym_signature] = "signature",
  [sym_block] = "block",
  [sym_designator] = "callStmt",
  [sym_primary] = "primary",
  [sym_qualIdent] = "qualIdent",
  [sym_builtinCall] = "builtinCall",
  [sym_realNumber] = "realNumber",
  [sym_stringLiteral] = "stringLiteral",
  [sym_escSeq] = "escSeq",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_fullVarDecl_repeat1] = "fullVarDecl_repeat1",
  [aux_sym_identList_repeat1] = "identList_repeat1",
  [aux_sym_exprList_repeat1] = "exprList_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_charLiteral_repeat1] = "charLiteral_repeat1",
  [alias_sym_shortVarDecl] = "shortVarDecl",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_fullVarDecl_token1] = aux_sym_fullVarDecl_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_decNumber] = sym_decNumber,
  [sym_hexNumber] = sym_hexNumber,
  [aux_sym_realNumber_token1] = aux_sym_realNumber_token1,
  [aux_sym_realNumber_token2] = aux_sym_realNumber_token2,
  [aux_sym_realNumber_token3] = aux_sym_realNumber_token3,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_charLiteral_token1] = aux_sym_charLiteral_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_escSeq_token1] = aux_sym_escSeq_token1,
  [aux_sym_escSeq_token2] = aux_sym_escSeq_token2,
  [sym_comment] = sym_comment,
  [sym_program] = sym_program,
  [sym_fullVarDecl] = sym_fullVarDecl,
  [sym_varDeclItem] = sym_varDeclItem,
  [sym_identList] = sym_identList,
  [sym_typedIdentList] = sym_typedIdentList,
  [sym_type] = sym_type,
  [sym_fnDecl] = sym_fnDecl,
  [sym_methodDecl] = sym_methodDecl,
  [sym_rcvSignature] = sym_rcvSignature,
  [sym_exprList] = sym_exprList,
  [sym_signature] = sym_signature,
  [sym_block] = sym_block,
  [sym_designator] = sym_designator,
  [sym_primary] = sym_primary,
  [sym_qualIdent] = sym_qualIdent,
  [sym_builtinCall] = sym_builtinCall,
  [sym_realNumber] = sym_realNumber,
  [sym_stringLiteral] = sym_stringLiteral,
  [sym_escSeq] = sym_escSeq,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_fullVarDecl_repeat1] = aux_sym_fullVarDecl_repeat1,
  [aux_sym_identList_repeat1] = aux_sym_identList_repeat1,
  [aux_sym_exprList_repeat1] = aux_sym_exprList_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_charLiteral_repeat1] = aux_sym_charLiteral_repeat1,
  [alias_sym_shortVarDecl] = alias_sym_shortVarDecl,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_fullVarDecl_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_decNumber] = {
    .visible = true,
    .named = true,
  },
  [sym_hexNumber] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_realNumber_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_realNumber_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_realNumber_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_charLiteral_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_escSeq_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escSeq_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_fullVarDecl] = {
    .visible = true,
    .named = true,
  },
  [sym_varDeclItem] = {
    .visible = true,
    .named = true,
  },
  [sym_identList] = {
    .visible = true,
    .named = true,
  },
  [sym_typedIdentList] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_fnDecl] = {
    .visible = true,
    .named = true,
  },
  [sym_methodDecl] = {
    .visible = true,
    .named = true,
  },
  [sym_rcvSignature] = {
    .visible = true,
    .named = true,
  },
  [sym_exprList] = {
    .visible = true,
    .named = true,
  },
  [sym_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_designator] = {
    .visible = true,
    .named = true,
  },
  [sym_primary] = {
    .visible = true,
    .named = true,
  },
  [sym_qualIdent] = {
    .visible = true,
    .named = true,
  },
  [sym_builtinCall] = {
    .visible = true,
    .named = true,
  },
  [sym_realNumber] = {
    .visible = true,
    .named = true,
  },
  [sym_stringLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_escSeq] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fullVarDecl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identList_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exprList_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_charLiteral_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_shortVarDecl] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_body = 2,
  field_defaultValue = 3,
  field_exported = 4,
  field_identifier = 5,
  field_identifiers = 6,
  field_module = 7,
  field_name = 8,
  field_params = 9,
  field_receiver = 10,
  field_signature = 11,
  field_type = 12,
  field_value = 13,
  field_values = 14,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_defaultValue] = "defaultValue",
  [field_exported] = "exported",
  [field_identifier] = "identifier",
  [field_identifiers] = "identifiers",
  [field_module] = "module",
  [field_name] = "name",
  [field_params] = "params",
  [field_receiver] = "receiver",
  [field_signature] = "signature",
  [field_type] = "type",
  [field_value] = "value",
  [field_values] = "values",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 1},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 3},
  [11] = {.index = 19, .length = 3},
  [12] = {.index = 22, .length = 1},
  [13] = {.index = 23, .length = 1},
  [14] = {.index = 24, .length = 4},
  [15] = {.index = 28, .length = 4},
  [16] = {.index = 32, .length = 4},
  [17] = {.index = 36, .length = 2},
  [18] = {.index = 38, .length = 2},
  [19] = {.index = 40, .length = 5},
  [20] = {.index = 45, .length = 2},
  [21] = {.index = 47, .length = 3},
  [22] = {.index = 50, .length = 4},
  [23] = {.index = 54, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_exported, 1},
  [1] =
    {field_exported, 1, .inherited = true},
  [2] =
    {field_name, 1},
    {field_signature, 2},
  [4] =
    {field_exported, 1},
    {field_exported, 2, .inherited = true},
  [6] =
    {field_exported, 0, .inherited = true},
    {field_exported, 1, .inherited = true},
  [8] =
    {field_identifiers, 0},
    {field_values, 2},
  [10] =
    {field_identifier, 0},
  [11] =
    {field_identifiers, 0},
    {field_value, 2},
  [13] =
    {field_exported, 2},
    {field_name, 1},
    {field_signature, 3},
  [16] =
    {field_body, 3},
    {field_name, 1},
    {field_signature, 2},
  [19] =
    {field_name, 2},
    {field_receiver, 1},
    {field_signature, 3},
  [22] =
    {field_exported, 2},
  [23] =
    {field_params, 1},
  [24] =
    {field_body, 4},
    {field_exported, 2},
    {field_name, 1},
    {field_signature, 3},
  [28] =
    {field_exported, 3},
    {field_name, 2},
    {field_receiver, 1},
    {field_signature, 4},
  [32] =
    {field_body, 4},
    {field_name, 2},
    {field_receiver, 1},
    {field_signature, 3},
  [36] =
    {field_identifier, 2},
    {field_module, 0},
  [38] =
    {field_name, 1},
    {field_type, 3},
  [40] =
    {field_body, 5},
    {field_exported, 3},
    {field_name, 2},
    {field_receiver, 1},
    {field_signature, 4},
  [45] =
    {field_defaultValue, 3},
    {field_params, 1},
  [47] =
    {field_arguments, 1},
    {field_arguments, 2},
    {field_name, 0},
  [50] =
    {field_arguments, 1},
    {field_arguments, 2},
    {field_arguments, 3},
    {field_name, 0},
  [54] =
    {field_arguments, 1},
    {field_arguments, 2},
    {field_arguments, 3},
    {field_arguments, 4},
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [6] = {
    [0] = alias_sym_shortVarDecl,
    [1] = alias_sym_shortVarDecl,
    [2] = alias_sym_shortVarDecl,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 16,
  [21] = 14,
  [22] = 17,
  [23] = 14,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 19,
  [33] = 33,
  [34] = 34,
  [35] = 27,
  [36] = 36,
  [37] = 37,
  [38] = 36,
  [39] = 18,
  [40] = 30,
  [41] = 37,
  [42] = 37,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 43,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 26,
  [55] = 55,
  [56] = 56,
  [57] = 24,
  [58] = 58,
  [59] = 15,
  [60] = 31,
  [61] = 44,
  [62] = 36,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 33,
  [71] = 71,
  [72] = 72,
  [73] = 25,
  [74] = 74,
  [75] = 28,
  [76] = 76,
  [77] = 48,
  [78] = 78,
  [79] = 79,
  [80] = 79,
  [81] = 56,
  [82] = 82,
  [83] = 53,
  [84] = 84,
  [85] = 63,
  [86] = 86,
  [87] = 50,
  [88] = 47,
  [89] = 49,
  [90] = 90,
  [91] = 52,
  [92] = 55,
  [93] = 58,
  [94] = 34,
  [95] = 95,
  [96] = 64,
  [97] = 97,
  [98] = 98,
  [99] = 51,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 86,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 104,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 106,
  [114] = 114,
  [115] = 111,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 117,
  [122] = 122,
  [123] = 123,
  [124] = 118,
  [125] = 119,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 31,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 33,
  [138] = 138,
  [139] = 132,
  [140] = 140,
  [141] = 47,
  [142] = 30,
  [143] = 143,
  [144] = 136,
  [145] = 131,
  [146] = 146,
  [147] = 136,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '"', 48,
        '\'', 43,
        '(', 18,
        ')', 21,
        '*', 23,
        ',', 24,
        '.', 8,
        '/', 4,
        ':', 26,
        ';', 31,
        '=', 22,
        '\\', 11,
        '{', 30,
        '}', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(48);
      if (lookahead == '/') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ';') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(48);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(52);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 11:
      ADVANCE_MAP(
        'x', 15,
        '0', 49,
        'a', 49,
        'b', 49,
        'e', 49,
        'f', 49,
        'n', 49,
        'r', 49,
        't', 49,
        'v', 49,
      );
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '(', 18,
        ')', 21,
        '*', 23,
        ',', 24,
        '.', 8,
        '/', 4,
        ':', 10,
        ';', 31,
        '=', 22,
        '{', 30,
        '}', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_fullVarDecl_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_fullVarDecl_token1);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == ';') ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_decNumber);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_hexNumber);
      if (lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_hexNumber);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_hexNumber);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_realNumber_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_realNumber_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_realNumber_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_charLiteral_token1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_charLiteral_token1);
      if (lookahead == '"') ADVANCE(48);
      if (lookahead == '/') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_charLiteral_token1);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_charLiteral_token1);
      ADVANCE_MAP(
        'x', 15,
        '0', 49,
        'a', 49,
        'b', 49,
        'e', 49,
        'f', 49,
        'n', 49,
        'r', 49,
        't', 49,
        'v', 49,
      );
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_escSeq_token1);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_escSeq_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'v') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 16},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 16},
  [29] = {.lex_state = 16},
  [30] = {.lex_state = 16},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 16},
  [33] = {.lex_state = 16},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 16},
  [40] = {.lex_state = 16},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 16},
  [44] = {.lex_state = 16},
  [45] = {.lex_state = 16},
  [46] = {.lex_state = 16},
  [47] = {.lex_state = 16},
  [48] = {.lex_state = 16},
  [49] = {.lex_state = 16},
  [50] = {.lex_state = 16},
  [51] = {.lex_state = 16},
  [52] = {.lex_state = 16},
  [53] = {.lex_state = 16},
  [54] = {.lex_state = 16},
  [55] = {.lex_state = 16},
  [56] = {.lex_state = 16},
  [57] = {.lex_state = 16},
  [58] = {.lex_state = 16},
  [59] = {.lex_state = 16},
  [60] = {.lex_state = 16},
  [61] = {.lex_state = 16},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 16},
  [64] = {.lex_state = 16},
  [65] = {.lex_state = 16},
  [66] = {.lex_state = 16},
  [67] = {.lex_state = 16},
  [68] = {.lex_state = 16},
  [69] = {.lex_state = 16},
  [70] = {.lex_state = 16},
  [71] = {.lex_state = 16},
  [72] = {.lex_state = 16},
  [73] = {.lex_state = 16},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 16},
  [76] = {.lex_state = 16},
  [77] = {.lex_state = 16},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 16},
  [80] = {.lex_state = 16},
  [81] = {.lex_state = 16},
  [82] = {.lex_state = 16},
  [83] = {.lex_state = 16},
  [84] = {.lex_state = 3},
  [85] = {.lex_state = 16},
  [86] = {.lex_state = 16},
  [87] = {.lex_state = 16},
  [88] = {.lex_state = 16},
  [89] = {.lex_state = 16},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 16},
  [92] = {.lex_state = 16},
  [93] = {.lex_state = 16},
  [94] = {.lex_state = 16},
  [95] = {.lex_state = 3},
  [96] = {.lex_state = 16},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 16},
  [99] = {.lex_state = 16},
  [100] = {.lex_state = 3},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 16},
  [103] = {.lex_state = 16},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 3},
  [106] = {.lex_state = 16},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 16},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 16},
  [113] = {.lex_state = 16},
  [114] = {.lex_state = 16},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 16},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 16},
  [127] = {.lex_state = 2},
  [128] = {.lex_state = 16},
  [129] = {.lex_state = 2},
  [130] = {.lex_state = 16},
  [131] = {.lex_state = 16},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 9},
  [134] = {.lex_state = 9},
  [135] = {.lex_state = 16},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 2},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 16},
  [141] = {.lex_state = 2},
  [142] = {.lex_state = 2},
  [143] = {.lex_state = 16},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 16},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_decNumber] = ACTIONS(1),
    [sym_hexNumber] = ACTIONS(1),
    [aux_sym_realNumber_token1] = ACTIONS(1),
    [aux_sym_realNumber_token2] = ACTIONS(1),
    [aux_sym_realNumber_token3] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_escSeq_token1] = ACTIONS(1),
    [aux_sym_escSeq_token2] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_program] = STATE(138),
    [sym_fullVarDecl] = STATE(8),
    [sym_identList] = STATE(135),
    [sym_fnDecl] = STATE(8),
    [sym_methodDecl] = STATE(8),
    [aux_sym_program_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(9),
    [anon_sym_fn] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      aux_sym_block_repeat1,
    STATE(29), 1,
      sym_qualIdent,
    STATE(71), 1,
      sym_primary,
    STATE(72), 1,
      sym_builtinCall,
    STATE(128), 1,
      sym_identList,
    STATE(69), 5,
      sym_fullVarDecl,
      sym_fnDecl,
      sym_methodDecl,
      sym_block,
      sym_designator,
  [41] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_block_repeat1,
    STATE(29), 1,
      sym_qualIdent,
    STATE(71), 1,
      sym_primary,
    STATE(72), 1,
      sym_builtinCall,
    STATE(128), 1,
      sym_identList,
    STATE(69), 5,
      sym_fullVarDecl,
      sym_fnDecl,
      sym_methodDecl,
      sym_block,
      sym_designator,
  [82] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      aux_sym_block_repeat1,
    STATE(29), 1,
      sym_qualIdent,
    STATE(71), 1,
      sym_primary,
    STATE(72), 1,
      sym_builtinCall,
    STATE(128), 1,
      sym_identList,
    STATE(69), 5,
      sym_fullVarDecl,
      sym_fnDecl,
      sym_methodDecl,
      sym_block,
      sym_designator,
  [123] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_ident,
    ACTIONS(15), 1,
      anon_sym_var,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_block_repeat1,
    STATE(29), 1,
      sym_qualIdent,
    STATE(71), 1,
      sym_primary,
    STATE(72), 1,
      sym_builtinCall,
    STATE(128), 1,
      sym_identList,
    STATE(69), 5,
      sym_fullVarDecl,
      sym_fnDecl,
      sym_methodDecl,
      sym_block,
      sym_designator,
  [164] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      sym_ident,
    ACTIONS(32), 1,
      anon_sym_var,
    ACTIONS(35), 1,
      anon_sym_fn,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      aux_sym_block_repeat1,
    STATE(29), 1,
      sym_qualIdent,
    STATE(71), 1,
      sym_primary,
    STATE(72), 1,
      sym_builtinCall,
    STATE(128), 1,
      sym_identList,
    STATE(69), 5,
      sym_fullVarDecl,
      sym_fnDecl,
      sym_methodDecl,
      sym_block,
      sym_designator,
  [205] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_COMMA,
    ACTIONS(51), 1,
      anon_sym_COLON_EQ,
    ACTIONS(53), 1,
      anon_sym_COLON_COLON,
    STATE(95), 1,
      aux_sym_identList_repeat1,
    ACTIONS(43), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(45), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [235] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(9), 1,
      anon_sym_var,
    ACTIONS(11), 1,
      anon_sym_fn,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(135), 1,
      sym_identList,
    STATE(12), 4,
      sym_fullVarDecl,
      sym_fnDecl,
      sym_methodDecl,
      aux_sym_program_repeat1,
  [260] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(59), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [277] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      aux_sym_realNumber_token3,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    STATE(68), 1,
      sym_exprList,
    ACTIONS(61), 2,
      sym_decNumber,
      sym_hexNumber,
    ACTIONS(63), 2,
      aux_sym_realNumber_token1,
      aux_sym_realNumber_token2,
    STATE(18), 2,
      sym_realNumber,
      sym_stringLiteral,
  [302] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    ACTIONS(75), 1,
      aux_sym_realNumber_token3,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    ACTIONS(71), 2,
      sym_decNumber,
      sym_hexNumber,
    ACTIONS(73), 2,
      aux_sym_realNumber_token1,
      aux_sym_realNumber_token2,
    STATE(110), 2,
      sym_realNumber,
      sym_stringLiteral,
  [327] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym_ident,
    ACTIONS(84), 1,
      anon_sym_var,
    ACTIONS(87), 1,
      anon_sym_fn,
    STATE(135), 1,
      sym_identList,
    STATE(12), 4,
      sym_fullVarDecl,
      sym_fnDecl,
      sym_methodDecl,
      aux_sym_program_repeat1,
  [352] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      aux_sym_realNumber_token3,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    STATE(102), 1,
      sym_exprList,
    ACTIONS(73), 2,
      aux_sym_realNumber_token1,
      aux_sym_realNumber_token2,
    ACTIONS(90), 2,
      sym_decNumber,
      sym_hexNumber,
    STATE(39), 2,
      sym_realNumber,
      sym_stringLiteral,
  [377] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      aux_sym_realNumber_token3,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    ACTIONS(73), 2,
      aux_sym_realNumber_token1,
      aux_sym_realNumber_token2,
    ACTIONS(92), 2,
      sym_decNumber,
      sym_hexNumber,
    STATE(88), 2,
      sym_realNumber,
      sym_stringLiteral,
  [399] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      aux_sym_exprList_repeat1,
    ACTIONS(94), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(98), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [419] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      aux_sym_realNumber_token3,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 2,
      aux_sym_realNumber_token1,
      aux_sym_realNumber_token2,
    ACTIONS(100), 2,
      sym_decNumber,
      sym_hexNumber,
    STATE(28), 2,
      sym_realNumber,
      sym_stringLiteral,
  [441] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      aux_sym_realNumber_token3,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    ACTIONS(73), 2,
      aux_sym_realNumber_token1,
      aux_sym_realNumber_token2,
    ACTIONS(102), 2,
      sym_decNumber,
      sym_hexNumber,
    STATE(139), 2,
      sym_realNumber,
      sym_stringLiteral,
  [463] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_exprList_repeat1,
    ACTIONS(104), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(106), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [483] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      aux_sym_exprList_repeat1,
    ACTIONS(108), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(113), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [503] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      aux_sym_realNumber_token3,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    ACTIONS(73), 2,
      aux_sym_realNumber_token1,
      aux_sym_realNumber_token2,
    ACTIONS(115), 2,
      sym_decNumber,
      sym_hexNumber,
    STATE(75), 2,
      sym_realNumber,
      sym_stringLiteral,
  [525] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      aux_sym_realNumber_token3,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    ACTIONS(117), 2,
      sym_decNumber,
      sym_hexNumber,
    ACTIONS(119), 2,
      aux_sym_realNumber_token1,
      aux_sym_realNumber_token2,
    STATE(141), 2,
      sym_realNumber,
      sym_stringLiteral,
  [547] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      aux_sym_realNumber_token3,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    ACTIONS(73), 2,
      aux_sym_realNumber_token1,
      aux_sym_realNumber_token2,
    ACTIONS(125), 2,
      sym_decNumber,
      sym_hexNumber,
    STATE(132), 2,
      sym_realNumber,
      sym_stringLiteral,
  [569] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      aux_sym_realNumber_token3,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(63), 2,
      aux_sym_realNumber_token1,
      aux_sym_realNumber_token2,
    ACTIONS(127), 2,
      sym_decNumber,
      sym_hexNumber,
    STATE(47), 2,
      sym_realNumber,
      sym_stringLiteral,
  [591] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_block,
    ACTIONS(134), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(129), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [610] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      sym_block,
    ACTIONS(141), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(136), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [629] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(34), 1,
      sym_block,
    ACTIONS(148), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(143), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [648] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
    STATE(55), 1,
      sym_block,
    ACTIONS(155), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(150), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [667] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(113), 4,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [682] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(161), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [699] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(165), 4,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [714] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(169), 4,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [729] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym_exprList_repeat1,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
    ACTIONS(108), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [748] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(176), 4,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [763] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(180), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [777] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
    STATE(92), 1,
      sym_block,
    ACTIONS(150), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [795] = 5,
    ACTIONS(184), 1,
      aux_sym_charLiteral_token1,
    ACTIONS(186), 1,
      anon_sym_DQUOTE,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(188), 2,
      aux_sym_escSeq_token1,
      aux_sym_escSeq_token2,
    STATE(74), 2,
      sym_escSeq,
      aux_sym_charLiteral_repeat1,
  [813] = 5,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(192), 1,
      aux_sym_charLiteral_token1,
    ACTIONS(194), 1,
      anon_sym_DQUOTE,
    ACTIONS(188), 2,
      aux_sym_escSeq_token1,
      aux_sym_escSeq_token2,
    STATE(36), 2,
      sym_escSeq,
      aux_sym_charLiteral_repeat1,
  [831] = 5,
    ACTIONS(184), 1,
      aux_sym_charLiteral_token1,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_DQUOTE,
    ACTIONS(188), 2,
      aux_sym_escSeq_token1,
      aux_sym_escSeq_token2,
    STATE(74), 2,
      sym_escSeq,
      aux_sym_charLiteral_repeat1,
  [849] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_exprList_repeat1,
    ACTIONS(104), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [867] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(165), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [881] = 5,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(200), 1,
      aux_sym_charLiteral_token1,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
    ACTIONS(188), 2,
      aux_sym_escSeq_token1,
      aux_sym_escSeq_token2,
    STATE(62), 2,
      sym_escSeq,
      aux_sym_charLiteral_repeat1,
  [899] = 5,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(204), 1,
      aux_sym_charLiteral_token1,
    ACTIONS(206), 1,
      anon_sym_DQUOTE,
    ACTIONS(188), 2,
      aux_sym_escSeq_token1,
      aux_sym_escSeq_token2,
    STATE(38), 2,
      sym_escSeq,
      aux_sym_charLiteral_repeat1,
  [917] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_ident,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym_fullVarDecl_repeat1,
    STATE(127), 1,
      sym_varDeclItem,
    STATE(134), 1,
      sym_identList,
    STATE(144), 1,
      sym_typedIdentList,
  [939] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_ident,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_fullVarDecl_repeat1,
    STATE(127), 1,
      sym_varDeclItem,
    STATE(134), 1,
      sym_identList,
    STATE(144), 1,
      sym_typedIdentList,
  [961] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      sym_ident,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_fullVarDecl_repeat1,
    STATE(127), 1,
      sym_varDeclItem,
    STATE(134), 1,
      sym_identList,
    STATE(144), 1,
      sym_typedIdentList,
  [983] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_ident,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_fullVarDecl_repeat1,
    STATE(127), 1,
      sym_varDeclItem,
    STATE(134), 1,
      sym_identList,
    STATE(144), 1,
      sym_typedIdentList,
  [1005] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(223), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1019] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(227), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1033] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(231), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1047] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(235), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1061] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(239), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1075] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(243), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1089] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(247), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1103] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
    STATE(94), 1,
      sym_block,
    ACTIONS(143), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1121] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(251), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1135] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(255), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1149] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
    STATE(99), 1,
      sym_block,
    ACTIONS(129), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1167] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(259), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1181] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(32), 1,
      aux_sym_exprList_repeat1,
    ACTIONS(94), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1199] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(169), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1213] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_ident,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_fullVarDecl_repeat1,
    STATE(127), 1,
      sym_varDeclItem,
    STATE(134), 1,
      sym_identList,
    STATE(144), 1,
      sym_typedIdentList,
  [1235] = 5,
    ACTIONS(184), 1,
      aux_sym_charLiteral_token1,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_DQUOTE,
    ACTIONS(188), 2,
      aux_sym_escSeq_token1,
      aux_sym_escSeq_token2,
    STATE(74), 2,
      sym_escSeq,
      aux_sym_charLiteral_repeat1,
  [1253] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(267), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1267] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(271), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1281] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(275), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1295] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(279), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1309] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(283), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1323] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_SEMI,
    ACTIONS(287), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(285), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1339] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_SEMI,
    ACTIONS(293), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(291), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1355] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(176), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1369] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(299), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1383] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(161), 3,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1397] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
    STATE(89), 1,
      sym_block,
    ACTIONS(136), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1415] = 5,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(301), 1,
      aux_sym_charLiteral_token1,
    ACTIONS(304), 1,
      anon_sym_DQUOTE,
    ACTIONS(306), 2,
      aux_sym_escSeq_token1,
      aux_sym_escSeq_token2,
    STATE(74), 2,
      sym_escSeq,
      aux_sym_charLiteral_repeat1,
  [1433] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
    ACTIONS(113), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1447] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(309), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1460] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(225), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1473] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_COMMA,
    ACTIONS(51), 1,
      anon_sym_COLON_EQ,
    ACTIONS(313), 1,
      anon_sym_COLON,
    STATE(95), 1,
      aux_sym_identList_repeat1,
  [1492] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_ident,
    ACTIONS(315), 1,
      anon_sym_LPAREN,
    STATE(96), 1,
      sym_varDeclItem,
    STATE(134), 1,
      sym_identList,
    STATE(136), 1,
      sym_typedIdentList,
  [1511] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_ident,
    ACTIONS(317), 1,
      anon_sym_LPAREN,
    STATE(64), 1,
      sym_varDeclItem,
    STATE(134), 1,
      sym_identList,
    STATE(147), 1,
      sym_typedIdentList,
  [1530] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(253), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1543] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
    ACTIONS(319), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1556] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(245), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1569] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_COMMA,
    ACTIONS(321), 1,
      anon_sym_COLON,
    ACTIONS(323), 1,
      anon_sym_COLON_EQ,
    STATE(90), 1,
      aux_sym_identList_repeat1,
  [1585] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      ts_builtin_sym_end,
    ACTIONS(265), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1597] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_ident,
    ACTIONS(325), 1,
      anon_sym_RPAREN,
    STATE(117), 1,
      sym_typedIdentList,
    STATE(134), 1,
      sym_identList,
  [1613] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
    ACTIONS(233), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1625] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    ACTIONS(221), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1637] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
    ACTIONS(229), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1649] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_COMMA,
    ACTIONS(327), 1,
      anon_sym_COLON,
    ACTIONS(329), 1,
      anon_sym_COLON_EQ,
    STATE(100), 1,
      aux_sym_identList_repeat1,
  [1665] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      ts_builtin_sym_end,
    ACTIONS(241), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1677] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      ts_builtin_sym_end,
    ACTIONS(249), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1689] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      ts_builtin_sym_end,
    ACTIONS(257), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1701] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(178), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1713] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_COMMA,
    ACTIONS(331), 1,
      anon_sym_COLON,
    ACTIONS(333), 1,
      anon_sym_COLON_EQ,
    STATE(100), 1,
      aux_sym_identList_repeat1,
  [1729] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
    ACTIONS(269), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1741] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_STAR,
    ACTIONS(339), 1,
      anon_sym_COLON,
    ACTIONS(337), 2,
      anon_sym_COMMA,
      anon_sym_COLON_EQ,
  [1755] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_ident,
    ACTIONS(343), 1,
      anon_sym_DOT_DOT,
    STATE(120), 1,
      sym_qualIdent,
    STATE(122), 1,
      sym_type,
  [1771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
    ACTIONS(237), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1783] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_COMMA,
    ACTIONS(348), 1,
      anon_sym_COLON,
    ACTIONS(350), 1,
      anon_sym_COLON_EQ,
    STATE(100), 1,
      aux_sym_identList_repeat1,
  [1799] = 2,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(352), 4,
      aux_sym_charLiteral_token1,
      anon_sym_DQUOTE,
      aux_sym_escSeq_token1,
      aux_sym_escSeq_token2,
  [1809] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 1,
      ts_builtin_sym_end,
    ACTIONS(356), 3,
      anon_sym_var,
      anon_sym_fn,
      sym_ident,
  [1821] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_ident,
    ACTIONS(358), 1,
      anon_sym_RPAREN,
    STATE(121), 1,
      sym_typedIdentList,
    STATE(134), 1,
      sym_identList,
  [1837] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      anon_sym_LPAREN,
    ACTIONS(362), 1,
      anon_sym_STAR,
    STATE(24), 1,
      sym_signature,
  [1850] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 1,
      anon_sym_COLON,
    ACTIONS(364), 2,
      anon_sym_COMMA,
      anon_sym_COLON_EQ,
  [1861] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 1,
      sym_ident,
    ACTIONS(370), 1,
      anon_sym_LPAREN,
    STATE(145), 1,
      sym_rcvSignature,
  [1874] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(372), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      aux_sym_exprList_repeat1,
  [1887] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      anon_sym_LPAREN,
    ACTIONS(376), 1,
      anon_sym_STAR,
    STATE(57), 1,
      sym_signature,
  [1900] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_ident,
    STATE(116), 1,
      sym_type,
    STATE(120), 1,
      sym_qualIdent,
  [1913] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    ACTIONS(378), 1,
      anon_sym_RPAREN,
    STATE(107), 1,
      aux_sym_exprList_repeat1,
  [1926] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      anon_sym_LPAREN,
    ACTIONS(380), 1,
      anon_sym_STAR,
    STATE(27), 1,
      sym_signature,
  [1939] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_COLON_COLON,
    ACTIONS(45), 2,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1950] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 1,
      anon_sym_LPAREN,
    ACTIONS(382), 1,
      sym_ident,
    STATE(131), 1,
      sym_rcvSignature,
  [1963] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_ident,
    STATE(120), 1,
      sym_qualIdent,
    STATE(146), 1,
      sym_type,
  [1976] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      anon_sym_LPAREN,
    ACTIONS(384), 1,
      anon_sym_STAR,
    STATE(35), 1,
      sym_signature,
  [1989] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(386), 2,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [1997] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(388), 1,
      anon_sym_RPAREN,
    ACTIONS(390), 1,
      anon_sym_EQ,
  [2007] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_signature,
  [2017] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      anon_sym_LPAREN,
    STATE(54), 1,
      sym_signature,
  [2027] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(392), 2,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [2035] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(394), 1,
      anon_sym_RPAREN,
    ACTIONS(396), 1,
      anon_sym_EQ,
  [2045] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(398), 2,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [2053] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 2,
      anon_sym_RPAREN,
      sym_ident,
  [2061] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      anon_sym_LPAREN,
    STATE(73), 1,
      sym_signature,
  [2071] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      anon_sym_LPAREN,
    STATE(26), 1,
      sym_signature,
  [2081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(400), 1,
      sym_ident,
  [2088] = 2,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(402), 1,
      aux_sym_fullVarDecl_token1,
  [2095] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(404), 1,
      anon_sym_COLON_EQ,
  [2102] = 2,
    ACTIONS(169), 1,
      aux_sym_fullVarDecl_token1,
    ACTIONS(190), 1,
      sym_comment,
  [2109] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(406), 1,
      sym_ident,
  [2116] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(408), 1,
      sym_ident,
  [2123] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(410), 1,
      anon_sym_RPAREN,
  [2130] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(412), 1,
      anon_sym_COLON,
  [2137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(414), 1,
      anon_sym_COLON,
  [2144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(416), 1,
      anon_sym_COLON_EQ,
  [2151] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(418), 1,
      anon_sym_EQ,
  [2158] = 2,
    ACTIONS(176), 1,
      aux_sym_fullVarDecl_token1,
    ACTIONS(190), 1,
      sym_comment,
  [2165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(420), 1,
      ts_builtin_sym_end,
  [2172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(422), 1,
      anon_sym_RPAREN,
  [2179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(424), 1,
      sym_ident,
  [2186] = 2,
    ACTIONS(190), 1,
      sym_comment,
    ACTIONS(223), 1,
      aux_sym_fullVarDecl_token1,
  [2193] = 2,
    ACTIONS(165), 1,
      aux_sym_fullVarDecl_token1,
    ACTIONS(190), 1,
      sym_comment,
  [2200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(426), 1,
      sym_ident,
  [2207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(428), 1,
      anon_sym_EQ,
  [2214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(430), 1,
      sym_ident,
  [2221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(432), 1,
      anon_sym_RPAREN,
  [2228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(434), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 123,
  [SMALL_STATE(6)] = 164,
  [SMALL_STATE(7)] = 205,
  [SMALL_STATE(8)] = 235,
  [SMALL_STATE(9)] = 260,
  [SMALL_STATE(10)] = 277,
  [SMALL_STATE(11)] = 302,
  [SMALL_STATE(12)] = 327,
  [SMALL_STATE(13)] = 352,
  [SMALL_STATE(14)] = 377,
  [SMALL_STATE(15)] = 399,
  [SMALL_STATE(16)] = 419,
  [SMALL_STATE(17)] = 441,
  [SMALL_STATE(18)] = 463,
  [SMALL_STATE(19)] = 483,
  [SMALL_STATE(20)] = 503,
  [SMALL_STATE(21)] = 525,
  [SMALL_STATE(22)] = 547,
  [SMALL_STATE(23)] = 569,
  [SMALL_STATE(24)] = 591,
  [SMALL_STATE(25)] = 610,
  [SMALL_STATE(26)] = 629,
  [SMALL_STATE(27)] = 648,
  [SMALL_STATE(28)] = 667,
  [SMALL_STATE(29)] = 682,
  [SMALL_STATE(30)] = 699,
  [SMALL_STATE(31)] = 714,
  [SMALL_STATE(32)] = 729,
  [SMALL_STATE(33)] = 748,
  [SMALL_STATE(34)] = 763,
  [SMALL_STATE(35)] = 777,
  [SMALL_STATE(36)] = 795,
  [SMALL_STATE(37)] = 813,
  [SMALL_STATE(38)] = 831,
  [SMALL_STATE(39)] = 849,
  [SMALL_STATE(40)] = 867,
  [SMALL_STATE(41)] = 881,
  [SMALL_STATE(42)] = 899,
  [SMALL_STATE(43)] = 917,
  [SMALL_STATE(44)] = 939,
  [SMALL_STATE(45)] = 961,
  [SMALL_STATE(46)] = 983,
  [SMALL_STATE(47)] = 1005,
  [SMALL_STATE(48)] = 1019,
  [SMALL_STATE(49)] = 1033,
  [SMALL_STATE(50)] = 1047,
  [SMALL_STATE(51)] = 1061,
  [SMALL_STATE(52)] = 1075,
  [SMALL_STATE(53)] = 1089,
  [SMALL_STATE(54)] = 1103,
  [SMALL_STATE(55)] = 1121,
  [SMALL_STATE(56)] = 1135,
  [SMALL_STATE(57)] = 1149,
  [SMALL_STATE(58)] = 1167,
  [SMALL_STATE(59)] = 1181,
  [SMALL_STATE(60)] = 1199,
  [SMALL_STATE(61)] = 1213,
  [SMALL_STATE(62)] = 1235,
  [SMALL_STATE(63)] = 1253,
  [SMALL_STATE(64)] = 1267,
  [SMALL_STATE(65)] = 1281,
  [SMALL_STATE(66)] = 1295,
  [SMALL_STATE(67)] = 1309,
  [SMALL_STATE(68)] = 1323,
  [SMALL_STATE(69)] = 1339,
  [SMALL_STATE(70)] = 1355,
  [SMALL_STATE(71)] = 1369,
  [SMALL_STATE(72)] = 1383,
  [SMALL_STATE(73)] = 1397,
  [SMALL_STATE(74)] = 1415,
  [SMALL_STATE(75)] = 1433,
  [SMALL_STATE(76)] = 1447,
  [SMALL_STATE(77)] = 1460,
  [SMALL_STATE(78)] = 1473,
  [SMALL_STATE(79)] = 1492,
  [SMALL_STATE(80)] = 1511,
  [SMALL_STATE(81)] = 1530,
  [SMALL_STATE(82)] = 1543,
  [SMALL_STATE(83)] = 1556,
  [SMALL_STATE(84)] = 1569,
  [SMALL_STATE(85)] = 1585,
  [SMALL_STATE(86)] = 1597,
  [SMALL_STATE(87)] = 1613,
  [SMALL_STATE(88)] = 1625,
  [SMALL_STATE(89)] = 1637,
  [SMALL_STATE(90)] = 1649,
  [SMALL_STATE(91)] = 1665,
  [SMALL_STATE(92)] = 1677,
  [SMALL_STATE(93)] = 1689,
  [SMALL_STATE(94)] = 1701,
  [SMALL_STATE(95)] = 1713,
  [SMALL_STATE(96)] = 1729,
  [SMALL_STATE(97)] = 1741,
  [SMALL_STATE(98)] = 1755,
  [SMALL_STATE(99)] = 1771,
  [SMALL_STATE(100)] = 1783,
  [SMALL_STATE(101)] = 1799,
  [SMALL_STATE(102)] = 1809,
  [SMALL_STATE(103)] = 1821,
  [SMALL_STATE(104)] = 1837,
  [SMALL_STATE(105)] = 1850,
  [SMALL_STATE(106)] = 1861,
  [SMALL_STATE(107)] = 1874,
  [SMALL_STATE(108)] = 1887,
  [SMALL_STATE(109)] = 1900,
  [SMALL_STATE(110)] = 1913,
  [SMALL_STATE(111)] = 1926,
  [SMALL_STATE(112)] = 1939,
  [SMALL_STATE(113)] = 1950,
  [SMALL_STATE(114)] = 1963,
  [SMALL_STATE(115)] = 1976,
  [SMALL_STATE(116)] = 1989,
  [SMALL_STATE(117)] = 1997,
  [SMALL_STATE(118)] = 2007,
  [SMALL_STATE(119)] = 2017,
  [SMALL_STATE(120)] = 2027,
  [SMALL_STATE(121)] = 2035,
  [SMALL_STATE(122)] = 2045,
  [SMALL_STATE(123)] = 2053,
  [SMALL_STATE(124)] = 2061,
  [SMALL_STATE(125)] = 2071,
  [SMALL_STATE(126)] = 2081,
  [SMALL_STATE(127)] = 2088,
  [SMALL_STATE(128)] = 2095,
  [SMALL_STATE(129)] = 2102,
  [SMALL_STATE(130)] = 2109,
  [SMALL_STATE(131)] = 2116,
  [SMALL_STATE(132)] = 2123,
  [SMALL_STATE(133)] = 2130,
  [SMALL_STATE(134)] = 2137,
  [SMALL_STATE(135)] = 2144,
  [SMALL_STATE(136)] = 2151,
  [SMALL_STATE(137)] = 2158,
  [SMALL_STATE(138)] = 2165,
  [SMALL_STATE(139)] = 2172,
  [SMALL_STATE(140)] = 2179,
  [SMALL_STATE(141)] = 2186,
  [SMALL_STATE(142)] = 2193,
  [SMALL_STATE(143)] = 2200,
  [SMALL_STATE(144)] = 2207,
  [SMALL_STATE(145)] = 2214,
  [SMALL_STATE(146)] = 2221,
  [SMALL_STATE(147)] = 2228,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qualIdent, 1, 0, 7),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualIdent, 1, 0, 7),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identList, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qualIdent, 3, 0, 17),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualIdent, 3, 0, 17),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exprList, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprList, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(139),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exprList, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exprList, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_exprList_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exprList_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exprList_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(141),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(142),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_methodDecl, 4, 0, 11),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_methodDecl, 4, 0, 11), SHIFT(5),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_methodDecl, 4, 0, 11),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_methodDecl, 5, 0, 15),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_methodDecl, 5, 0, 15), SHIFT(5),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_methodDecl, 5, 0, 15),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fnDecl, 4, 0, 9),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_fnDecl, 4, 0, 9), SHIFT(5),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fnDecl, 4, 0, 9),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fnDecl, 3, 0, 3),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_fnDecl, 3, 0, 3), SHIFT(5),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fnDecl, 3, 0, 3),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_realNumber, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_realNumber, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stringLiteral, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringLiteral, 2, 0, 0),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exprList_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stringLiteral, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringLiteral, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fnDecl, 5, 0, 14),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fnDecl, 5, 0, 14),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(137),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fullVarDecl_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fullVarDecl_repeat1, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDeclItem, 3, 0, 8),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDeclItem, 3, 0, 8),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_signature, 5, 0, 20),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signature, 5, 0, 20),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_methodDecl, 6, 0, 19),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_methodDecl, 6, 0, 19),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_methodDecl, 5, 0, 16),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_methodDecl, 5, 0, 16),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_signature, 3, 0, 13),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signature, 3, 0, 13),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fnDecl, 4, 0, 10),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fnDecl, 4, 0, 10),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_signature, 2, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signature, 2, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fullVarDecl, 4, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fullVarDecl, 4, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fullVarDecl, 3, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fullVarDecl, 3, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fullVarDecl, 2, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fullVarDecl, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtinCall, 5, 0, 23),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtinCall, 5, 0, 23),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtinCall, 4, 0, 22),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtinCall, 4, 0, 22),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtinCall, 3, 0, 21),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtinCall, 3, 0, 21),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 3, 0, 6),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 3, 0, 6),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [291] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_designator, 1, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_designator, 1, 0, 0),
  [301] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_charLiteral_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [304] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_charLiteral_repeat1, 2, 0, 0),
  [306] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_charLiteral_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [309] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 4, 0, 6),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 4, 0, 6),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identList, 1, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [319] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [321] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identList, 2, 0, 1),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identList, 2, 0, 1),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [327] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identList, 3, 0, 4),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identList, 3, 0, 4),
  [331] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identList, 2, 0, 2),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identList, 2, 0, 2),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identList_repeat1, 2, 0, 0),
  [339] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_identList_repeat1, 2, 0, 0),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [345] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identList_repeat1, 2, 0, 5), SHIFT_REPEAT(130),
  [348] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_identList_repeat1, 2, 0, 5),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identList_repeat1, 2, 0, 5),
  [352] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escSeq, 1, 0, 0),
  [354] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 3, 0, 6),
  [356] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 3, 0, 6),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [364] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identList_repeat1, 3, 0, 12),
  [366] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_identList_repeat1, 3, 0, 12),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [386] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typedIdentList, 4, 0, 0),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [392] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [398] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typedIdentList, 3, 0, 0),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [420] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [424] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rcvSignature, 5, 0, 18),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [430] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [432] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [434] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_umka(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
